Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/bionic64"
   config.vm.box_check_update = false
   config.vm.network :private_network, ip: "192.168.6.89"
   config.vm.hostname = "www.digitalport.local"

   config.vm.network "forwarded_port", guest: 80, host: 80
   config.vm.synced_folder "../site", "/var/www/digitalport"

   config.vm.provision "shell", path: "additional_packages.sh"
   config.vm.provision "shell", path: "mysql.sh"
   config.vm.provision "shell", path: "laravel.sh"
end